export const GET_LIST_INTERVAL_DEFAULT = 100;
export const GET_LIST_RETRY_DEFAULT = 3;
export const POST_FORM_INTERVAL_MIN_DEFAULT = 100;
export const POST_FORM_INTERVAL_MAX_DEFAULT = 200;
export const POST_FORM_RETRY_DEFAULT = 10;
export const WAIT_INTERVAL_DEFAULT = 100;
